apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.19.*
      chart: cert-manager
      helm:
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      path: infrastructure/cert-manager
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
