apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://community-charts.github.io/helm-charts"
      chart: cloudflared
      targetRevision: 2.2.*
      helm:
        valueFiles:
          - $values/infrastructure/cloudflared/cf-config.yaml
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
