apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://community-charts.github.io/helm-charts"
      chart: cloudflared
      targetRevision: 2.2.*
      helm:
        values: |
          replicaCount: 3

          tunnel:
            existingSecret: tunnel-credentials

          env:
            - name: TUNNEL_ID
              valueFrom:
                secretKeyRef:
                  name: tunnel-credentials
                  key: tunnel-id

          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
            - $(TUNNEL_ID)

    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      path: infrastructure/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
