apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      path: infrastructure/longhorn/longhorn-namespace
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.*
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
