apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://victoriametrics.github.io/helm-charts/
    chart: victoria-metrics-k8s-stack
    targetRevision: 0.66.*
    helm:
      values: |
        fullnameOverride: "vm-stack"

        vmsingle:
          spec:
            retentionPeriod: "14d"
            resources:
              requests:
                cpu: "1"
                memory: "1Gi"
            storage:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi

        grafana:
          enabled: true
          deploymentStrategy:
            type: Recreate
            rollingUpdate: null
          persistence:
            enabled: true
            size: 5Gi
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"

  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoria-metrics-operator-validation
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-operator-admission
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
