apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts/
      chart: victoria-metrics-k8s-stack
      targetRevision: 0.66.*
      helm:
        valueFiles:
          - $values/infrastructure/victoria-metrics/values.yaml
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      targetRevision: HEAD
      ref: values
    - repoURL: "https://github.com/Kyleg142/nostramo-lab.git"
      path: infrastructure/victoria-metrics
      targetRevision: HEAD

  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-metrics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: victoria-metrics-stack-victoria-metrics-operator-validation
      jsonPointers:
        - /data
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: victoria-metrics-stack-victoria-metrics-operator-admission
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
    - group: ""
      kind: Secret
      name: victoria-metrics-stack-grafana
      jsonPointers:
        - /data
